vm eastwest iop should be based on empty profile
GoogleCloudPlatform/anthos-service-mesh-packages pull request #526
Opened 2021-03-05 22:40 UTC by stevenctl

Without this, the IstioOperator will overwrite other parts of the installation. 

the istiod deployment/service, mutating webhook configmap/config, validating webhook config and probably a ton of other things end up with `install.operator.istio.io/owning-resource: eastwest` which is incorrect.

2021-03-05 22:41 UTC, stevenctl commented
We had this here, not sure why it wasn't copied over:

https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/b7cff407f77d74c4b7fb750b4cd853059cac80eb/asm/istio/expansion/vm-eastwest-gateway.yaml#L21

2021-03-05 22:57 UTC, stevenctl commented
AFAIK ASM doesn't use the istio operator controller at all, but if it did, this would probably cause issues.

2021-03-05 23:00 UTC, jasonwzm commented
These are two different use cases. The vm.yaml file is for install_asm when we add it as an overlay.

2021-03-05 23:02 UTC, stevenctl commented
If that's the case, we probably don't want to set `name` in `vm.yaml`?

2021-03-05 23:06 UTC, jasonwzm commented
Oh I did not notice that. Yes, that makes sense. We can remove metadata field from this yaml.

2021-03-05 23:47 UTC, jasonwzm commented
It does not seem your new change is pushed.

2021-03-06 00:05 UTC, jasonwzm requested changes

2021-03-06 00:05 UTC, jasonwzm commented on asm/istio/options/vm.yaml
> +                targetPort: 15021+
Is this a typo?

2021-03-06 00:06 UTC, stevenctl commented on asm/istio/options/vm.yaml
> +                targetPort: 15021+
yep...

2021-03-06 00:07 UTC, jasonwzm approved these changes

2021-03-08 06:51 UTC, jasonwzm commented
/gcbrun

2021-03-08 07:42 UTC, merged